### ISSUE TITLE
PdfViewer not a valid SSR component

### ISSUE THREAD

**Issue by pitzzahh** [vinodnimbalkar/svelte-pdf#73]
```js
Error: <PdfViewer> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <PdfViewer>.
    at Module.validate_component (C:\Users\peter\web-projects\test-pdf\node_modules\.pnpm\svelte@4.2.12\node_modules\svelte\src\runtime\internal\ssr.js:126:9)
    at C:\Users\peter\web-projects\test-pdf\src\routes\+page.svelte:25:42
    at Object.$$render (C:\Users\peter\web-projects\test-pdf\node_modules\.pnpm\svelte@4.2.12\node_modules\svelte\src\runtime\internal\ssr.js:156:16)
    at Object.default (C:\Users\peter\web-projects\test-pdf\.svelte-kit\generated\root.svelte:45:41)
    at C:\Users\peter\web-projects\test-pdf\node_modules\.pnpm\@sveltejs+kit@2.5.2_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.1.4\node_modules\@sveltejs\kit\src\runtime\components\layout.svelte:5:41
    at Object.$$render (C:\Users\peter\web-projects\test-pdf\node_modules\.pnpm\svelte@4.2.12\node_modules\svelte\src\runtime\internal\ssr.js:156:16)
    at C:\Users\peter\web-projects\test-pdf\.svelte-kit\generated\root.svelte:44:40
    at $$render (C:\Users\peter\web-projects\test-pdf\node_modules\.pnpm\svelte@4.2.12\node_modules\svelte\src\runtime\internal\ssr.js:156:16)
    at Object.render (C:\Users\peter\web-projects\test-pdf\node_modules\.pnpm\svelte@4.2.12\node_modules\svelte\src\runtime\internal\ssr.js:164:17)
    at Module.render_response (C:\Users\peter\web-projects\test-pdf\node_modules\.pnpm\@sveltejs+kit@2.5.2_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.1.4\node_modules\@sveltejs\kit\src\runtime\server\page\render.js:171:29)
```

**Comment by vinodnimbalkar** [comment]
Fix by https://github.com/vinodnimbalkar/svelte-pdf/commit/f51093bc2646484fadc6b12c4f93e5b6e0425bfa
